### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'log/bimeanvae/amzn/ex1/pytorch_model.bin'

### ISSUE THREAD

**Issue by YuChen17Heaven** [megagonlabs/coop#1]
After I trained this model, I evaluate this and it has such errno

**Comment by isomap** [comment]
Hi, @YuChen17Heaven! Thank you for your interest, and sorry to make confusion!

Could you give us more information about it? For example, the commands to run the training and evaluation. Also, it is really helpful if you can provide more error messages.

Thank you!

**Comment by YuChen17Heaven** [comment]
Hi @isomap , I solved it. Thanks for your reply.

**Comment by isomap** [comment]
Good to hear that! Please feel free to let us know if you have any other issues :)
